name: pynterpred
channels:
  - conda-forge
  - omnia
  - anaconda
  - defaults
dependencies:
  - intel-openmp=2018.0.0=8
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - mkl=2018.0.2=1
  - mkl-rt=11.1=p0
  - sphinxcontrib=1.0=py36h6d0f590_1
  - alabaster=0.7.10=py36_1
  - alembic=0.9.9=py_0
  - asn1crypto=0.24.0=py36_0
  - astropy=3.0.2=py36_1
  - attrs=18.1.0=py_0
  - babel=2.5.3=py36_0
  - backcall=0.1.0=py_0
  - backports=1.0=py36_1
  - backports.functools_lru_cache=1.5=py36_0
  - bhmm=0.6.2=py36_0
  - biopython=1.71=py36_0
  - blas=1.1=openblas
  - bleach=2.1.3=py_0
  - blosc=1.14.0=1
  - boto3=1.7.12=py_0
  - botocore=1.10.12=py_0
  - bzip2=1.0.6=1
  - ca-certificates=2018.4.16=0
  - cairo=1.14.10=0
  - cerberus=1.2=py36_0
  - certifi=2018.4.16=py36_0
  - cffi=1.11.5=py36_0
  - chardet=3.0.4=py36_0
  - clyent=1.2.2=py36_0
  - cryptography=2.2.1=py36_0
  - curl=7.59.0=1
  - cycler=0.10.0=py36_0
  - cython=0.28.2=py36_0
  - dbus=1.11.0=0
  - decorator=4.3.0=py_0
  - dill=0.2.7.1=py36_0
  - docopt=0.6.2=py36_0
  - docutils=0.14=py36_0
  - entrypoints=0.2.3=py36_1
  - et_xmlfile=1.0.1=py36_0
  - expat=2.2.5=0
  - fastcache=1.0.2=py36_0
  - fontconfig=2.12.6=0
  - freetype=2.8.1=0
  - gettext=0.19.8.1=0
  - glib=2.55.0=0
  - gmp=6.1.2=0
  - gmpy2=2.0.8=py36_1
  - griddataformats=0.4.0=py_0
  - gsd=1.5.1=py36_0
  - gst-plugins-base=1.8.0=0
  - gstreamer=1.8.0=1
  - h5py=2.7.1=py36_2
  - hdf4=4.2.13=0
  - hdf5=1.10.1=2
  - healpy=1.11.0=py36_1
  - html5lib=1.0.1=py_0
  - icu=58.2=0
  - idna=2.6=py36_1
  - imagesize=1.0.0=py36_0
  - ipykernel=4.8.2=py36_0
  - ipython=6.3.1=py36_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.2.1=py36_1
  - jdcal=1.4=py36_0
  - jedi=0.12.0=py36_0
  - jinja2=2.10=py36_0
  - jmespath=0.9.3=py36_0
  - joblib=0.11=py36_0
  - jpeg=9b=2
  - jsonschema=2.6.0=py36_1
  - jupyter_client=5.2.3=py36_0
  - jupyter_contrib_core=0.3.3=py36_1
  - jupyter_core=4.4.0=py_0
  - jupyter_nbextensions_configurator=0.4.0=py36_0
  - jupyterlab=0.32.1=py36_0
  - jupyterlab_launcher=0.10.5=py36_0
  - kiwisolver=1.0.1=py36_1
  - krb5=1.14.6=0
  - latexcodec=1.0.5=py36_0
  - libffi=3.2.1=3
  - libiconv=1.15=0
  - libnetcdf=4.6.1=2
  - libpng=1.6.34=0
  - libsodium=1.0.16=0
  - libssh2=1.8.0=2
  - libxcb=1.13=0
  - libxml2=2.9.8=0
  - llvmlite=0.23.0=py36_1
  - lzo=2.10=0
  - mako=1.0.7=py36_0
  - markupsafe=1.0=py36_0
  - matplotlib=2.2.2=py36_1
  - mdtraj=1.9.1=py36_1
  - mistune=0.8.3=py36_1
  - mmtf-python=1.1.0=py_0
  - mock=2.0.0=py36_0
  - more-itertools=4.1.0=py_0
  - mpc=1.1.0=4
  - mpfr=3.1.5=0
  - mpi=1.0=mpich
  - mpi4py=3.0.0=py36_0
  - mpich=3.2.1=0
  - mpmath=1.0.0=py_0
  - msgpack-python=0.5.6=py36_0
  - msmtools=1.2.1=py36_1
  - multiprocess=0.70.5=py36_0
  - natsort=5.3.0=py_0
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py36_0
  - ncurses=5.9=10
  - netcdf4=1.3.1=py36_3
  - networkx=2.1=py36_0
  - nglview=1.0=py36_1
  - notebook=5.4.1=py36_0
  - numba=0.38.0=py36_0
  - numexpr=2.6.5=py36_0
  - numpy=1.14.3=py36_blas_openblas_200
  - numpydoc=0.8.0=py36_0
  - openblas=0.2.20=7
  - openpyxl=2.5.3=py36_0
  - openssl=1.0.2o=0
  - oset=0.1.3=py36_0
  - packaging=17.1=py_0
  - pamela=0.3.0=py36_0
  - pandas=0.22.0=py36_1
  - pandoc=2.2=0
  - pandocfilters=1.4.2=py36_0
  - parso=0.2.0=py_0
  - path.py=10.3.1=py36_0
  - pathos=0.2.1=py36_1
  - patsy=0.5.0=py36_0
  - pbr=4.0.2=py_0
  - pcre=8.41=1
  - pexpect=4.5.0=py36_0
  - pickleshare=0.7.4=py36_0
  - pint=0.8.1=py36_0
  - pip=9.0.3=py36_0
  - pixman=0.34.0=2
  - pluggy=0.6.0=py_0
  - pox=0.2.3=py36_0
  - ppft=1.6.4.7.1=py36_0
  - progress_reporter=1.4.1=py_0
  - prompt_toolkit=1.0.15=py36_0
  - psutil=5.4.5=py36_0
  - ptyprocess=0.5.2=py36_0
  - py=1.5.3=py_0
  - pybtex=0.21=py36_0
  - pybtex-docutils=0.2.1=py36_0
  - pycparser=2.18=py36_0
  - pygments=2.2.0=py36_0
  - pymbar=3.0.3=py36_1
  - pyopenssl=17.5.0=py36_1
  - pyparsing=2.2.0=py36_0
  - pyqt=5.6.0=py36_5
  - pysocks=1.6.8=py36_1
  - pytables=3.4.3=py36_8
  - pytest=3.5.1=py36_0
  - pytest-arraydiff=0.2=py_0
  - pytest-astropy=0.2.1=py_0
  - pytest-doctestplus=0.1.2=py_0
  - pytest-openfiles=0.2.0=py_0
  - pytest-remotedata=0.2.0=py_0
  - pytest-runner=4.2=py_0
  - python=3.6.5=1
  - python-dateutil=2.7.2=py_0
  - python-editor=1.0.3=py36_0
  - python-oauth2=1.0.1=py36_0
  - pytz=2018.4=py_0
  - pyyaml=3.12=py36_1
  - pyzmq=17.0.0=py36_4
  - qt=5.6.2=7
  - quaternion=2018.5.2.21.39.8=py36_0
  - readline=7.0=0
  - requests=2.18.4=py36_1
  - s3transfer=0.1.13=py36_0
  - scikit-learn=0.19.1=py36_blas_openblas_201
  - scipy=1.0.1=py36_blas_openblas_200
  - send2trash=1.5.0=py_0
  - setuptools=39.1.0=py36_0
  - simplegeneric=0.8.1=py36_0
  - sip=4.18=py36_1
  - six=1.11.0=py36_1
  - snowballstemmer=1.2.1=py36_0
  - sphinx=1.7.4=py36_0
  - sphinxcontrib-bibtex=0.4.0=py36_0
  - sphinxcontrib-websupport=1.0.1=py36_0
  - sqlalchemy=1.2.7=py36h65ede16_0
  - sqlite=3.20.1=2
  - statsmodels=0.8.0=py36_0
  - sympy=1.1.1=py36_0
  - terminado=0.8.1=py36_0
  - testpath=0.3.1=py36_0
  - thermotools=0.2.6=py36_2
  - tk=8.6.7=0
  - tornado=5.0.2=py36_0
  - tqdm=4.23.2=py_0
  - traitlets=4.3.2=py36_0
  - typing=3.6.4=py36_0
  - urllib3=1.22=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5=py36_0
  - wheel=0.31.0=py36_0
  - widgetsnbextension=3.2.1=py36_0
  - xorg-libxau=1.0.8=3
  - xorg-libxdmcp=1.1.2=3
  - xz=5.2.3=0
  - yaml=0.1.7=0
  - zeromq=4.2.5=1
  - zlib=1.2.11=0
  - ambermini=16.16.0=7
  - clusterutils=0.3.1=py36_0
  - fftw3f=3.3.4=2
  - openmm=7.2.1=py36_1
  - openmmtools=0.15.0=py36_0
  - openmoltools=0.8.3=py36_0
  - parmed=3.0.1=py36_1
  - pdbfixer=1.5=py36_0
  - pip:
    - numpy-quaternion==2018.5.2.21.39.8
    - tables==3.4.3
prefix: /home/diego/Myopt/Miniconda/miniconda3/envs/pynterpred

